//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由动软.Net代码生成器生成。
//     运行库版本:2.5
//
//     请根据项目的实际情况，修改该模板。
// </auto-generated>
//------------------------------------------------------------------------------

namespace JiaJiao.Web.Teacher {
    
    
    /// <summary>
    /// Add 类。
    /// </summary>
    /// <remarks>
    /// 自动生成的类。
    /// </remarks>
    public partial class Add 
    {
        
		protected global::System.Web.UI.WebControls.TextBox txtTeacherName;
		protected global::System.Web.UI.WebControls.TextBox txtTeacherTel;
		protected global::System.Web.UI.WebControls.TextBox txtTeacherEmail;
		protected global::System.Web.UI.WebControls.TextBox txtTeacherAddress;
		protected global::System.Web.UI.WebControls.TextBox txtTeacherDescribe;
		protected global::System.Web.UI.WebControls.TextBox txtRoleId;
		protected global::System.Web.UI.WebControls.TextBox txtCreateTime;
		protected global::System.Web.UI.WebControls.TextBox txtUpdateTime;
	protected global::System.Web.UI.WebControls.Button btnSave;
	protected global::System.Web.UI.WebControls.Button btnCancel;


        
    }
}
