//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由动软.Net代码生成器生成。
//     运行库版本:2.5
//
//     请根据项目的实际情况，修改该模板。
// </auto-generated>
//------------------------------------------------------------------------------

namespace JiaJiao.Web.Teacher {
    
    
    /// <summary>
    /// Show 类。
    /// </summary>
    /// <remarks>
    /// 自动生成的类。
    /// </remarks>
    public partial class Show {
        	protected global::System.Web.UI.WebControls.Label lblID;
	protected global::System.Web.UI.WebControls.Label lblTeacherName;
	protected global::System.Web.UI.WebControls.Label lblTeacherTel;
	protected global::System.Web.UI.WebControls.Label lblTeacherEmail;
	protected global::System.Web.UI.WebControls.Label lblTeacherAddress;
	protected global::System.Web.UI.WebControls.Label lblTeacherDescribe;
	protected global::System.Web.UI.WebControls.Label lblRoleId;
	protected global::System.Web.UI.WebControls.Label lblCreateTime;
	protected global::System.Web.UI.WebControls.Label lblUpdateTime;


       
    }
}
